### ISSUE TITLE
Рейтинг сообщества

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxForum#16]
Добавить возможность лайкать/дизлайкать посты.

Сумма лайков/дизлайков под постами пользователя образует рейтинг сообщества пользователя.
Рейтинг сообщества пользователя должен уменьшаться на 2 раз в неделю (если отрицательный, то увеличиваться на 2 в неделю).

Карма >= 50 - лайки юзера приносят по +3 к рейтингу сообщества (дизлайков не касается, они продолжают давать -1).
Карма >= 30 - лайки юзера приносят по +2 к рейтингу сообщества (дизлайков не касается, они продолжают давать -1).

Сумма лайков под постами и изменений кармы в день не может превышать карму игрока.

Ограничения кармы не работают на людей с функциональными плашками: энфорсеров, лидов, сенаторов, педалей, разработчиков, модераторов форума/дискорда. Если у таких людей карма <5, то менять карму и лайкать посты в сумме они могут не более чем 5 раз в день.

**Comment by Epicus7** [comment]
Почти полностью реализовал тут:
https://github.com/ChaoticOnyx/OnyxForum/commit/bd95b8fa9b2d7a062fbc7fdbdd41b5451020efe9

Осталось:
1. Вывод подсказки при наведении на счетчик лайков кто лайкнул/дизлайкнул с разделением по их весу
2. Счетчик рейтинга сообщества - сумма лайков на всех постах с уменьшением по времени.

**Comment by Zert0X** [comment]
> Добавить возможность лайкать/дизлайкать посты.
> 
> Сумма лайков/дизлайков под постами пользователя образует рейтинг сообщества пользователя. Рейтинг сообщества пользователя должен уменьшаться на 2 раз в неделю (если отрицательный, то увеличиваться на 2 в неделю).
> 
> Карма >= 50 - лайки юзера приносят по +3 к рейтингу сообщества (дизлайков не касается, они продолжают давать -1). Карма >= 30 - лайки юзера приносят по +2 к рейтингу сообщества (дизлайков не касается, они продолжают давать -1).
> 
> Сумма лайков под постами и изменений кармы в день не может превышать карму игрока.
> 
> Ограничения кармы не работают на людей с функциональными плашками: энфорсеров, лидов, сенаторов, педалей, разработчиков, модераторов форума/дискорда. Если у таких людей карма <5, то менять карму и лайкать посты в сумме они могут не более чем 5 раз в день.

Может лучше не наводить на счётчик, а нажимать?
![изображение](https://user-images.githubusercontent.com/42303535/181002326-5803b73b-5115-49e3-9ba2-dd7dd939d47e.png)
