### ISSUE TITLE
Привязка ckey-я к дискорду на форуме

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxForum#18]
Перенести логику из бота Chaotic на форум в профиль

**Comment by Doster-d** [comment]
Разве нельзя в базе данных этого бота искать соответствие по дискорд ИДу?

**Comment by Epicus7** [comment]
Можно, но проблема в том, что без привязки сикея - многие функции форума будут недоступны пользователю. И это неоч логично, что чтобы получить эти функции - надо лезть в какого-то левого бота и разбираться с ним. Гораздо удобнее было бы, если бы привязать можно было прямо на форуме.

Ну и вообще, многие фичи Чаотика лучше перенести на форум, ибо там пользоваться ими будет удобнее. Я вряд ли буду переносить баги-и-идеи, но вот привязку аккаунтов и проверку баланса опиксов - это лучше на форум перенести.
