### ISSUE TITLE
У подфорумов указан неправильный путь форума

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxForum#83]
Открываем подфорум:
![image](https://user-images.githubusercontent.com/5204667/191282880-e9b8c7bd-1c2c-4f7f-9f71-c101163671b5.png)

В пути нет названия форума, внутри которого находится подфорум:
![image](https://user-images.githubusercontent.com/5204667/191284465-df9025bf-49eb-43de-a302-763e879f3161.png)

**Comment by Zert0X** [comment]
![изображение](https://user-images.githubusercontent.com/42303535/191526196-1beb4224-136f-44d6-a7a0-24662c4b8123.png)

Повторить не удалось
