### ISSUE TITLE
Все ссылки ведут в "Space Station 13"

### ISSUE THREAD

**Issue by igorsaux** [ChaoticOnyx/OnyxForum#97]
![15123](https://user-images.githubusercontent.com/55196698/191643793-7fad9393-a16c-42a9-8da4-f8e1924d96bf.png)

Опытным путём выяснилось что любая ссылка вида `https://community.ss13.ru/category/[любое число]-[любой текст]` ведёт в одну и ту же категорию - "Space Station 13"

**Comment by Epicus7** [comment]
Исправил
https://github.com/ChaoticOnyx/OnyxForum/commit/c3fff0e745fcdb01f51639a1d421d5eb15644c8c
